id = "jetbrains-rider-dark"
name = "JetBrains Rider Dark"
version = "0.0.1"
schema_version = 1
authors = ["RajaSunrise <indra020204@gmail.com>"]
description = "Dark JetBrains Rider themes"
repository = "https://github.com/NarmadaWeb/jetbrains-rider-zed"
